KnownAcpRuntime {
    id: "hermes",
    label: "Hermes Agent",
    commands: &["hermes-acp", "hermes"],
    aliases: &["hermes-agent"],
    avatar_url: "",
    mcp_command: None,
    mcp_hooks: false,
    underlying_cli: None,
    cli_install_commands: &[],
    cli_install_commands_windows: &[],
    adapter_install_commands: &[],
    cli_install_instructions_url:
        "https://hermes-agent.nousresearch.com/docs/getting-started/installation",
    adapter_install_instructions_url:
        "https://hermes-agent.nousresearch.com/docs/user-guide/features/acp",
    cli_install_hint: "Install Hermes Agent and ensure `hermes-acp` or `hermes` is available on PATH.",
    adapter_install_hint:
        "Hermes includes its ACP adapter. Configure a provider with `hermes model` or `hermes acp --setup`.",
    skill_dir: None,
    supports_acp_model_switching: true,
    model_env_var: None,
    provider_env_var: None,
    provider_locked: false,
    default_env: &[("HERMES_ACP_SKIP_CONFIGURED_MCP", "1")],
    config_file_path: Some("~/.hermes/config.yaml"),
    config_file_format: Some("yaml"),
    supports_acp_native_config: false,
    thinking_env_var: None,
    max_tokens_env_var: None,
    context_limit_env_var: None,
    required_normalized_fields: &[],
    login_hint: Some("Run `hermes model` or `hermes acp --setup` to configure a provider."),
    auth_probe_args: None,
}
